[project]
name = "mazegen"
version = "1.0.0"
authors = [
  {name="svpanfil", email="svpanfil@student.codam.nl"},
  {name="dpohulia", email="dpohulia@student.codam.nl"},
]
description = "Maze Generator"
readme = "README.md"
requires-python = ">=3.9"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
	"License :: OSI Approved :: MIT License",
]

[project.urls]
Homepage = "https://projects.intra.42.fr/a-maze-ing/dpohulia"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
